[project]
name = "vibe-claude-git-autosync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llm>=0.26",
    "llm-anthropic>=0.17",
    "llm-fragments-github>=0.4",
]
