name: Test git-autosync

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Make scripts executable
      run: |
        chmod +x git-autosync
        chmod +x test-git-autosync.sh

    - name: Run tests
      run: ./test-git-autosync.sh ./git-autosync

    - name: Test script directly (basic validation)
      run: |
        # Test that the script fails gracefully when not in a git repo
        ! ./git-autosync 2>/dev/null || exit 1
        echo "Script correctly fails when not in git repo"
